# Generated by Django 4.0.5 on 2022-06-15 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(blank=True, default=0, verbose_name='заказ №')),
                ('price_usd', models.PositiveIntegerField(blank=True, default=0, verbose_name='стоимость,$')),
                ('delivery_time', models.DateField(blank=True, default=datetime.date(1970, 1, 1), verbose_name='срок поставки')),
                ('price_rub', models.PositiveIntegerField(blank=True, default=0, verbose_name='стоимость,₽')),
            ],
        ),
    ]
